### ISSUE TITLE
Is this library trimmable

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/FSharp.Data.Adaptive#104]
I am using this library in blazor application, but the size of this library is 1713kb after published. Is it possible to make it trimmable?

**Comment by krauthaufen** [comment]
Hey, what do you mean by trimmable? I'm not familiar with the term but I assume some sort of dead-code removal?

**Comment by albertwoo** [comment]
Here is the article from MS: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

Simply speaking, if this library is not using reflection then is should be ok to add:
```xml
<TrimMode>link</TrimMode>
<IsTrimmable>true</IsTrimmable>
```

But need to verify that.

**Comment by krauthaufen** [comment]
It is actually using some reflection bits for building cheap(conservarive) equality comparisons

**Comment by albertwoo** [comment]
It may need extra work to annotate that.

**Comment by krauthaufen** [comment]
Basically reflection usage quite limited and iirc only used ror generating these equality-comparers, so it should be fairly easy to get that running, for some datastructures there's a specialized cheap equals method afair which is then used by the reflection code. If you want to look for these things yourself `ShallowEquality` is the thing to look for. When I have a little time I can investigate this myself but it might take a few days 
Cheers

**Comment by krauthaufen** [comment]
I quickly took a look and it basically boils down to one helper functions that is only called via reflection, all the other things should be fine as long as the trimming process doesn't remove fields from types, sadly I also can't offer any guarantees that this will work. Maybe publishing the test trimmed could be sufficient to show that nothing crucial gets removed...

**Comment by krauthaufen** [comment]
Just to be clear here we need to build the core library with net6.0 for that to work right?

**Comment by krauthaufen** [comment]
I have it running in a branch `trimmed-publish` and a very simple test works

```
> ls -lh FSharp.Data.Adaptive.dll 
-rw-r--r--  1 schorsch  staff    35K  1 May 19:39 FSharp.Data.Adaptive.dll
> ./PublishTrimmedTest   
20
200
```

I'll test some more things but it looks good so far

**Comment by krauthaufen** [comment]
After some local tests I think this works properly. I'm getting properly trimmed binaries and everything I tested still works as intended.

I'll just get a new version out now so you can test your project with it and I expect nothing to break in absence of trimming.

**Comment by albertwoo** [comment]
@krauthaufen it works so great. Currently no errors. And the bundle size is 134B in compressed in br format for my app.

So great!!! Thanks for your great and quick job!!! 👍🚀

**Comment by krauthaufen** [comment]
Nice, out of curiosity: what are you using it for?

**Comment by albertwoo** [comment]
I am building a nuget library for F# developers to write blazor application. Similar to bolero but in my own optionated way.
https://github.com/slaveOftime/Fun.Blazor

**Comment by krauthaufen** [comment]
Cool, nice to see the library in use 👍
