### ISSUE TITLE
AMap

### ISSUE THREAD

**Issue by krauthaufen** [fsprojects/FSharp.Data.Adaptive#11]
migrate from Aardvark.Base

**Comment by krauthaufen** [comment]
conceptually maps do not really compose in adaptive-world since colliding values cannot easily be represented.

Aardvark.Base.Incremental circumvents this problem via not implementing things like `AMap.union : aset<amap<_,_>>`.

If we want combinators like this we need to figure out clean semantics for it. possibilities are:
* multi-maps
* take-any-maps
* explicit merge functions (basically like foldGroup)

**Comment by dsyme** [comment]
> conceptually maps do not really compose in adaptive-world since colliding values cannot easily be represented.

Meaning binary operations on maps are hard to support?

I think that sounds fine in v0.1, binary operations on maps are surprisingly rarely used?

**Comment by krauthaufen** [comment]
binary can actually be handled (see https://github.com/aardvark-platform/aardvark.base/bloob/master/src/Aardvark.Base.Incremental/AdaptiveMap/amap.fs#L293) but n-ary is super tricky...

**Comment by krauthaufen** [comment]
at least when N is adaptive 😀

**Comment by krauthaufen** [comment]
basic combinators will do for 0.0.1.
