### ISSUE TITLE
NullPointerException in MultiCallbackObject when Mark is called by two thread and all the weak references have been garbage collected

### ISSUE THREAD

**Issue by patrickallensimpson** [fsprojects/FSharp.Data.Adaptive#112]
I was experiencing a NullPointerException in a Fun.Blazor application while reading entries from a Http Content stream asynchronously. This code would read an event and then append to a cval that was then used by an adaptiview component to render a Text field. This works most of the time but occasionally a NullPointerException is thrown and it doesn't make any sense from the code you've written.

Upon examining the location line 105 of the Mark() call in MultiCallbackObject  in Callbacks.fs I noticed that the check x call returns true when obj has already been cleared. Obviously if the check decides to remove the obj reference to allow it to be garbage collected then if another call to check occurs then it ought to return false if obj is null.

`
    let check (x : MultiCallbackObject) =
        if cbs.Value.Count = 0 && not (isNull (obj :> obj)) then
            obj.Outputs.Remove x |> ignore
            if lock table (fun () -> table.Remove obj) then
                level <- 0
                obj <- Unchecked.defaultof<_>
                weak <- null
                false
            else
                true
        else
            true
`
this should be
`
    let check (x : MultiCallbackObject) =
        if isNull (obj :> obj) then
            false
        elif cbs.Value.Count = 0 then
            obj.Outputs.Remove x |> ignore
            if lock table (fun () -> table.Remove obj) then
                level <- 0
                obj <- Unchecked.defaultof<_>
                weak <- null
                false
            else
                true
        else
            true
`

this way Mark() on line 105 will not attempt to add itself as an Output to the none existing obj ref:

`
        if check x then
            obj.Outputs.Add x |> ignore
`

Am I missing something in my understanding of this section of code?

I'll be glad to create a pull request for this change.

By the way this is VERY hard to make happen because you need to create weak callbacks that will get garbage collected but still get a Mark to occur! I could create a simple test example.

**Comment by krauthaufen** [comment]
merged
