### ISSUE TITLE
Consider hiding abstract members of AdaptiveMap and AdaptiveSet

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.Adaptive#20]
Looking at these kind of type definitions:
```
[<Interface>]
type AdaptiveHashSet<'T> =
    /// is the set constant?
    abstract member IsConstant : bool

    /// the current content of the set as aval.
    abstract member Content : aval<HashSet<'T>>
    
    /// gets a new reader to the set.
    abstract member GetReader : unit -> IHashSetReader<'T>
```

I'm tempted to propose that we merge AdaptiveMap.fs and ChangeableMap.fs and hide the abstract members behind a signature.  This would mean that no one can directly implement these interfaces - but it would also give us a lot of flexibility to change the implementations going forward - adding new members and so on.  We can still provide a way to implement the interfaces by providing three function definitions.

Note that F# currently doesn't allow internal abstract members - you can only achieve this by hiding the whole type definition like this:
```
type AdaptiveHashMap<'Key,'Value> 

type amap<'Key,'Value> = AdaptiveHashMap<'Key,'Value>
```

**Comment by krauthaufen** [comment]
will do, once I'm done with alist...

**Comment by krauthaufen** [comment]
Sorry I'm confused now.
The following won't compile:

```fsharp
type AdaptiveHashSet<'T>

[<Sealed>]
type ChangeableHashSet<'T> =
    (* inherit/interface/???? AdaptiveHashSet *)
    // ...
```
Am I missing something here?
I could certainly go for an adapter (ASet.ofCSet) but that's a little verbose on the user-side...

**Comment by krauthaufen** [comment]
i could make it an abstract class with a private constructor, but that would be quite OOPish....

**Comment by krauthaufen** [comment]
okay I thought about removing the interface and I think it doesn't really help a lot. actually a UI/rendering library will need all of those things. we could replace it with module functions, but that doesn't really help much either. I think the possibility to implement these things doesn't really expose anything dangerous. It's the same for seq in FSharp.Core actually.
what do you think?

**Comment by dsyme** [comment]
ok, agreed :)
