### ISSUE TITLE
Missing operators

### ISSUE THREAD

**Issue by krauthaufen** [fsprojects/FSharp.Data.Adaptive#31]
Keeping track of missing combinators here

### Currently not implemented

* ~`AMap.ofASet`~
* ~`AList.try(At|Get)`~
* ~`AMap.tryFind`~
* ~`AMap.fold(Group|HalfGroup)`~
* ~`AList.ofAVal`~
* ~`ASet.sortWith`~
* ~`AList.toASet`~
* ~`ASet.ofAList`~
* ~`AList.sort`~
* ~`ASet.sort`~
* ~`ASet.mapToMap`~
* ~`AMap.keys`~
* ~`ASet.sortBy`~
* ~`AList.sortWith`~
* ~`AList.sortBy`~

**Comment by krauthaufen** [comment]
all done, will close the issue for the moment

**Comment by dsyme** [comment]
Fantastic!
