### ISSUE TITLE
aval/aset/alist/amap non-generic

### ISSUE THREAD

**Issue by krauthaufen** [fsprojects/FSharp.Data.Adaptive#33]
In our old implementation we had a `IMod` interface which provided `GetValue : AdaptiveToken -> obj`.
The reason for that mainly was to allow for heterogenous collections of changeable values in our rendering engine (uniform inputs for shaders, etc.)

I think that adding it would severely reduce the cleanness of the API but we need some way of capturing untyped avals for our rendering engine.

Basically we would need GADTs for representing these existential types but the .NET code simulating that is rather verbose:

```fsharp
type AValVisitor<'r> =
    abstract member Accept<'a> : aval<'a> -> 'r
type AVal =
    abstract member Visit : AValVisitor<'r> -> 'r
```

This would allow aval<a> to get wrapped into one of these and we could 'extract' the generic Argument later on...

A different approach would be to explicitly 'upcast' to `aval<obj>` but since .NET doesn't support this we would need to create a new aval and use a mapping function, which really destroys the type-information and blows up the dependency graph.

Any better ideas for solving this problem in a cleaner way?

**Comment by dsyme** [comment]
It's a pretty normal pattern to just have a non-generic base type.  It opens up other reflection programming patterns too.

What if they are not given abbreviations?  So `AdaptiveValue`, `AdaptiveHashSet` etc. Then client code can define the abbreviations if necessary?

**Comment by krauthaufen** [comment]
sounds like a plan...
Actually we currently only use these for AVal, so maybe we can skip the others for the time being...

**Comment by krauthaufen** [comment]
I added a non-generic `AdaptiveValue`, so I'll close this for now...
