### ISSUE TITLE
Get list item by index as a aval

### ISSUE THREAD

**Issue by Thecentury** [fsprojects/FSharp.Data.Adaptive#34]
Hi!

Is it possible to get item of alist by index as an aval?

**Comment by krauthaufen** [comment]
Hey, not yet but I'll add it to the list of missing things (see https://github.com/fsprojects/FSharp.Data.Adaptive/issues/31)

However it's not entirely clear if it shall take an `Index` or an `int`....

**Comment by Thecentury** [comment]
@krauthaufen What's the difference between `clist` and `alist`?

**Comment by krauthaufen** [comment]
clist is a changeable input (you can add/remove elements imperatively) whereas alist is either a clist or some dependent list (constructed via AList.map/etc)

I'll try to write some simple examples once I'm finished with porting the library...
