### ISSUE TITLE
FSharp.Core 4.7 support

### ISSUE THREAD

**Issue by debugnik** [fsprojects/FSharp.Data.Adaptive#40]
I wanted to try the library and immediately found that the NuGet package has an constraint `< 4.7.0` on FSharp.Core. I assumed that wasn't intentional, so I installed it by forcing the FSharp.Core version as `== 4.7` on Paket, and the API seems to work fine. I guess the upper bound should be lifted?

**Comment by krauthaufen** [comment]
yep, will do...
I'm just used to SemVer so i tend to be a little over-conservative with dependency versions but I think the used F# features won't be changed any time soon...

**Comment by krauthaufen** [comment]
should be resolved via https://github.com/fsprojects/FSharp.Data.Adaptive/commit/d1af5129b47b02d28d0fef9cdb13b6e2b3d7bd04, package version `0.0.3` on nuget.
Cheers
