### ISSUE TITLE
Exception support in transaction?

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/FSharp.Data.Adaptive#43]
Looking at [this code](https://github.com/fsprojects/FSharp.Data.Adaptive/blob/b7a826a209085e7fd395a555f229f5f46fcf3306/src/FSharp.Data.Adaptive/Core/Transaction.fs#L233) it seems that transaction context might get corrupted in cases where the transaction body throws. I'm not too certain but it seems like the restoration statement should be placed in a finally clause.

**Comment by krauthaufen** [comment]
Good catch 😀
I'll fix that...

**Comment by krauthaufen** [comment]
should be fixed...
