### ISSUE TITLE
AList.chooseAdaptive etc.

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.Adaptive#46]
I found myself in need of an `AList.chooseAdaptive`, e,g,

    val chooseAdaptive: ('T -> aval<'U option>) -> alist<'T> -> alist<'U>

I expect the same is true for `existsAdaptive`, `mapAdaptive` and so on.  Some of these may already exist under different names.

**Comment by krauthaufen** [comment]
Hey I'll port them from Aardvark.Base.Incremental soon...
For `aset` these things exist and are called `chooseA`, `mapA`, etc.

All reasonable combinators I thought about so far (just comment if i forgot something)
* `forall(A)`
* `exists(A)`
* `map(A)` / `choose(A)` / `filter(A)`
* `sumByA` (although that one might not be efficient, so maybe a bad idea)

P.S.: Any opinions on the naming convention here?

**Comment by krauthaufen** [comment]
added `chooseA`/`filterA`/`mapA`/`reduceByA` that should  be capably of expressing all these things.
Note that the `chooseA`/`filterA`/`mapA` are only tested by by elmish example currently...

We should add some tests for these...

**Comment by krauthaufen** [comment]
Btw. here's a little snippet defining `forallA` and `existsA` using the new `AdaptiveReduction` that could help until I added these things to the lib...

```fsharp

/// some 'missing' alist combinators
module AList =
    let forallA (mapping: Index -> 'a -> aval<bool>) (list: alist<'a>) =
        let r = AdaptiveReduction.countNegative |> AdaptiveReduction.mapOut (fun v -> v = 0)
        AList.reduceByA r mapping list
        
    let existsA (mapping: Index -> 'a -> aval<bool>) (list: alist<'a>) =
        let r = AdaptiveReduction.countPositive |> AdaptiveReduction.mapOut (fun v -> v <> 0)
        AList.reduceByA r mapping list
```

**Comment by krauthaufen** [comment]
added a few more combinators for `alist`.
Need to leave now, but these things should be implemented for `aset` and `amap` respectively.

things to think about:
* `tryExactlyOne`
* `minBy`, `maxBy`
* `skip`, `truncate`

**Comment by krauthaufen** [comment]
A little update:

`aset` and `amap` now too provide lots of reductions like `forall(A)`, `exists(A)`, `sumBy(A)`, etc.

the `mapA`, `chooseA`, `filterA` combinators for `amap` are still missing but I think these won't be required too often...

**Comment by krauthaufen** [comment]
just added `AMap.chooseA/filterA/mapA` since implementing them was quite easy given the `AList` reader implementation...

**Comment by krauthaufen** [comment]
Closing this for now, since most of the combinators are implemented.

**Comment by dsyme** [comment]
👍
