### ISSUE TITLE
AList.init/AList.range and ranges of integers

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.Adaptive#50]
From Discord:

> Hey, a question - what's the best way to adaptively generate a range of integers, e.g. I have adaptive values `min` and `max` and I want an `AList` for `min` .. `max`?
> 
> Feels like we might be missing an `AList.init : aval<int> -> (int -> 'T) -> alist<'T>`?  Possibly also an `AList.range` of some kind which might be more efficient?

**Comment by dsyme** [comment]
@krauthaufen replied:
> hey, yep `AList.range` wouldn't be that hard to do...
> `init` could also be done actually
>
> `AList.initA : aval<int> -> (int -> aval<'T>) -> alist<'T>` could also be wanted sometimes

**Comment by krauthaufen** [comment]
done in https://github.com/fsprojects/FSharp.Data.Adaptive/pull/51
