### ISSUE TITLE
AList - missing pairwise

### ISSUE THREAD

**Issue by sandeepc24** [fsprojects/FSharp.Data.Adaptive#53]
I don't see function `AList.pairwise`, is it called something else? 

If it is not there can it be added?

**Comment by krauthaufen** [comment]
Hey, no it's not inplemented but it could certainly be done. I'll look into that when i have the time.

**Comment by haraldsteinlechner** [comment]
i stumbled a across it quite some times but did not yet implemented it. however just a note and also maybe a workaround: often falling back  from `alist<'a>` to `aval<list<'a>>` is a reasonable choice especially in cases when per-element operations are cheap or the collection often changes as a whole.
combinators like toAVal are good starting points in such situations https://github.com/fsprojects/FSharp.Data.Adaptive/blob/master/src/FSharp.Data.Adaptive/AdaptiveIndexList/AdaptiveIndexList.fsi#L125

**Comment by krauthaufen** [comment]
Hey, I finally got my head around this and implemented
* `IndexList.pairwise`
* `IndexList.pairwiseCyclic`
* `AList.pairwise`
* `AList.pairwiseCyclic`
