### ISSUE TITLE
missing ASet.groupBy

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#60]
```
groupBy (f : 'a -> 'g) (set : aset<'a>) : amap<'g, HashSet<'a>>
```
At the moment I'm using a local utility function:
```
set |> ASet.map (fun v -> (f(v), v)) |> AMap.ofASet
```
Our old implementation had a GroupByReader. Would there be benefits implementing something similar? In any case adding grouping convenience utlities might be considered.

**Comment by krauthaufen** [comment]
currently not really efficient but existing
