### ISSUE TITLE
Is IndexList.IndexOf complexity correct?

### ISSUE THREAD

**Issue by Thecentury** [fsprojects/FSharp.Data.Adaptive#61]
IndexList has `IndexOf by Index` operation:

```fs
/// Tries to find the position for the given Index or -1 if the Index does not exist. O(N)
member x.IndexOf(index : Index) =
    MapExt.tryIndexOf index content |> Option.defaultValue -1
```

Is its complexity really `O(N)`? I looked into the implementation and it seems to be a search in a binary tree, therefore having the `O(log(N))` complexity, isn't it?

**Comment by krauthaufen** [comment]
Correct, thanks for the report, I will fix that soon...
Btw. many of the hashmap/hashset complexities are actually O(min(32,log N)) but I annotated them with log N...

**Comment by krauthaufen** [comment]
done, thanks again!
