### ISSUE TITLE
CompiledName for HashSet/HashMap

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#67]
When using FSharp.Data.Adaptive.HashSet and System.Collection.Generic.HashSet together it requires to use fully qualified names or typedefs. It would be nice if this could be avoided by giving the HashSet a different name.

@krauthaufen You already had a suggestion to resolve this, could you evaluate the situation and have a look at this?

**Comment by krauthaufen** [comment]
I struggled a lot with this name but it after a while I figured that there simply is no other consistent name for that...

In F# it's not that big a problem actually but i see the problem for C#...

**Comment by krauthaufen** [comment]
Maybe we could call it FSharpHashSet (like the fsharp.core collections) via a CompiledName attribute...

**Comment by luithefirst** [comment]
I'm also struggling with liking alternative names. 

Right, as there is already a convention in the FSharp.Core (`List` as `FSharpList`), it would be an option to also apply it in our case.

Btw, what happened to the "Immutable" prefixes that we used some time ago?

**Comment by krauthaufen** [comment]
Hey, I personally like the FSharp prefixes since C# programmers interacting with F# are used to that...
The immutable prefixes would also collide with the System.Collections.Immutable names, so maybe we should stick with the FSharp prefix, since it avoids collisions until FSharp.Core gets a HashSet (which we should then use anyways)

**Comment by luithefirst** [comment]
So it looks like using CompiledName to avoid ambiguities for C# users is the way to go, I would be happy with that change :)
