### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by gsomix** [fsprojects/FSharp.Data.Adaptive#71]
From Aardvark Discord server:

> dsyme 11.06.2020
> Also I think we should probably just bump F.D.A. to version 1.0.0 and use SemVer from now on?  The library is rock solid as far as I can tell, the testing strategy is very good and it's based on well tested code
> 
> krauthaufen 11.06.2020
> Yep, we could definitely do that.

**Comment by krauthaufen** [comment]
I already did that yesterday and will start upgrading adaptify, etc in the next days

**Comment by gsomix** [comment]
Oh, I totally missed that! Thank you!
