### ISSUE TITLE
Improved GetValue in case of up-to-date AdaptiveObjects

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#74]
When using the adpative system in pulling scenarios there typically is an excessive amount of `GetValue` calls on adaptive objects that are not out-of-date. I've reviewed the current implementation and have been thinking about possible optimizations. 

Case 1: `ChangeableValue` used as `IAdaptiveValue`
When using `GetValue` instead of the `Value` property, the performance is much worse. I also noticed that the property getter does not reset `OutOfDate`, so it is actually required to use `GetValue` as otherwise callbacks would no longer be invoked when only the `Value` property is used. So maybe we should also reset `OutOfDate` there. Anyway, here is the proposed improved `GetValue` method:
```
member x.GetValue (token: AdaptiveToken) =
    if Unchecked.isNull token.Caller then
        x.OutOfDate <- false
        value
    else
        x.EvaluateAlways token (fun _ ->
            value
        )
```
Issue: AfterEvaluateCallbacks would not be invoked if used.

Case 2: `AbstractVal`
Similar to `ChangeableValue`, an optimization for top-level evaluations in the up-to-case should be valid:
```
member x.GetValue(token: AdaptiveToken) =
    if not x.OutOfDate && Unchecked.isNull token.Caller then
        valueCache
    else
        x.EvaluateAlways token (fun token ->
            if x.OutOfDate then
                let v = x.Compute token
                valueCache <- v
                v
            else
                valueCache                
        )
```
I assume performing `x.Compute` without locking can potentially result in a redundant concurrent evaluation. If we are not out-of-date and perform a top-level evaluation it should not matter if we race with an out-of-date marking in another thread and retrieve the current value.

Possible general issue: Maybe we also want to check the evaluation depth together with the caller. I'm not sure if it is valid to use an `AdaptiveToken.Top` when recursively updating the dependency graph.

Here is a benchmark with a comparison of the proposed changes:
|                    Method |       Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |-----------:|----------:|----------:|-------:|------:|------:|----------:|
|   CValGetValue (proposed) |   3.888 ns | 0.0520 ns | 0.0461 ns |      - |     - |     - |         - |
|    CValGetValue (current) |  27.910 ns | 0.3370 ns | 0.2990 ns |      - |     - |     - |         - |
| AValueGetValue (proposed) |   4.541 ns | 0.0727 ns | 0.0607 ns |      - |     - |     - |         - |
|  AValueGetValue (current) |  29.520 ns | 0.3100 ns | 0.2750 ns |      - |     - |     - |         - |
|     CValUpdate (proposed) | 991.300 ns | 7.7600 ns | 7.2600 ns | 0.1297 |     - |     - |     816 B |
|      CValUpdate (current) | 987.500 ns | 7.8300 ns | 6.9400 ns | 0.1259 |     - |     - |     792 B |

* CValGetValue: Repeatedly pulling an up-to-date `ChangeableValue `using `GetValue`
* AValueGetValue: Repeatedly pulling an up-to-date `AbstractVal`
* CValUpdate: Transaction changing a `CVal` and evaluating 3 linked `MapVal` that are always out-of-date

A possibility to (1) get rid of checking token.Caller (and evaluation depth) and (2) removing the overhead in case non-top callers would be to add `GetValue()` (without an AdaptiveToken) to the `IAdaptiveValue` interface so we can directly distinguish this special case.

If this optimization is valid, we could also implement that in the Map/Set/List internals.

All the unit tests pass with the two proposed changes. I'm not sure how extensive they cover multi-threading scenarios, but I can also not think of any scenarios where the changes would cause an issue. Maybe someone can think of a case and extend the tests accordingly. I'm looking forward to your input.

**Comment by krauthaufen** [comment]
> ... it should not matter if we race with an out-of-date marking in another thread and retrieve the current value.

The problem are not races on the cache but actually races on `OutOfDate` and the thing you're proposing (without locking) can sadly cause invalid states in the whole system, which in turn can cause all sorts of crazy things, like *stuck*  dependencies, etc.

> I'm not sure how extensive they cover multi-threading scenarios, but I can also not think of any scenarios where the changes would cause an issue. 

Not really, since testing MultiThreading/Concurrency can't really be done in a reasonable way.

Nonetheless we could try to improve `GetValue` here. How does the whole thing perform when actually locking the object?

**Comment by krauthaufen** [comment]
Oh, now I'm getting your point (my bad). When not changing the `OutOfDate` flag worst-case scenario is reading it just before the objects gets marked `OutOfDate` and fetching an *old* cache value (which changes the behaviour a little but doesn't make things wrong. 

However all of this assumes, that fetching the cache-value is atomic (no half-written caches) which we sadly cannot guarantee for structs (reading half old, half new values), so I don't think we should do that this way. How would your Benchmarks look like when still using locking?

**Comment by luithefirst** [comment]
Right, in the `cval` case race on `OutOfDate` might break the state. E.g. when a thread wants to set it to true and this is immediately undone by a getter. So maybe we want to also check for OutOfDate=false in the `cval `case, then races should not be an issue and in the worst case only an out-dated value might be returned, but again with large structs you might get partially overwritten values?

With locking the performance would already significantly decreases and I actually started from the `Value` getter of `cval` that actually already does this without locking, but using it is dangerous as it does not reset callbacks.

**Comment by krauthaufen** [comment]
> ... but again with large structs you might get partially overwritten values?

actually everything beyond 64bits. I think the locking at this point can't be dropped and it should actually be added to `cval.Value` in order to avoid half-written values.

Btw. I think that `~30ns` for getting a value aren't too bad after all (a virtual call alone taking something around '~4ns`)

**Comment by luithefirst** [comment]
E.g.: I use(d) GetValue in a photon mapper to get the material properties (10+ including a clist #75) at every hit and actually most are directly `cval` and change rarely. By switching to the Value, I could noticeably increase performance, but it breaks callbacks. After longer consideration, the clean way to avoid this would be to change the input data structure to a non-additive one. Unfortunately, this means a lot of additional work, that I've simply skipped. I also ignored that if there is a change that actually my rendering result is invalid. And the way I currently handle this, by simply re-tracing everything might consecutively result in invalid states if there are constant changes (we also call render loop).

I guess the conclusion would make it consistent by also locking in the `Value` property.

Do you think it would be a worthy improvement to handle TopLevel evaluations separately?

**Comment by krauthaufen** [comment]
I think the limiting factor here might just be virtual calls, so maybe we should consider looking for optimization-potential inside `EvaluateAlways` for top-level evaluations. Have you considered storing all material-properties in a single `cval`? This could reduce overhead significantly in your scenario and (since changes are rare) not drastically affect other things?

**Comment by luithefirst** [comment]
I would consider the data structure as given. It has a perfectly fitting architecture for UI bindings and our rendering backend. It becomes clear that an intermediate (immutable) view is needed for this use-case. At the moment there are some methods like `Sample` directly in the material that are used for offline rendering. Changing this to `aval<Sampler>` would kind of provide that what you are suggesting.
In general, `GetValue` shows up in profiles all the time. E.g. there are also some update threads that constantly pull multiple values. For that, I could actually implement my own `AdaptiveObject` that allows this fast cached access. This would be a lazy solution I would say.

So I would not consider any proposed changes to be integrated. The only potentially open point is the Value property of `cval`, but maybe also just want to keep it that way. On the other hand, the getter would be expected to do the same as `GetValue` (with potential for top-level evaluation optimization) and the setter being the equivalent of `UpdateTo` (already the case).
