### ISSUE TITLE
change UpdateTo returning bool notifying if the AdaptiveObject has changed

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#76]
This change would allow usage patterns like this:
```
ChangeableValue<bool> m_alphaBlending = AdaptiveValue.Init(false);

public bool AlphaBlending
{
    get { return m_alphaBlending.Value; }
    set 
    { 
        if (m_alphaBlending.UpdateTo(value)) 
        { 
            UpdateGeneration();
            this.Raise(value);
        } 
    }
}
```

**Comment by krauthaufen** [comment]
One problem with that will be, that `cval` only uses `ShallowEquality`, so changing the value may return true even if the value didn't change structurally. Nonetheless we would need return a `bool` in `UpdateTo` for `cset`, `clist`, `cval`, `cmap` when doing this

**Comment by luithefirst** [comment]
I already took a look at the other collections and they have a similar "early" check, but right it's not true equality. I came to this proposal as I tried to implement my own setter with this information in a generic way and ended up using ShallowEqualityComparer as generic equality is quite limited in .net. 
I guess we could still make this change as it does not change any behavior and document how the result needs to be interpreted. So it would not notify about an actual change, it notifies if the marking was triggered and a shallow equality test is used.

**Comment by luithefirst** [comment]
I just noticed that `cval` uses `DefaultEquality` and not shallow, so this is would this give the true equality result and behavior that is expected?

At the same time I also noticed that when setting arrays, there seems to be a deep comparison and not just a reference check? I'm not sure how I like that if this is the case when I think about Aardvark vertex/index buffer updates.

**Comment by krauthaufen** [comment]
Sorry, my bad. Of course cset uses "real" equality and therefore i opted to do the same in cval...
Totally forgot about that.

I think we should definitely include the boolean return with the next major version then...

**Comment by krauthaufen** [comment]
done in `v110` branch for `cset`, `clist`, `cmap` and `cval`
