### ISSUE TITLE
Implement interfaces like IList, ICollection, IDictionary in changeable collections

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#77]
It would nice to be able to pass the changeable collections around using the .net collection interfaces instead of the concrete collection type. This would also allow using routines with restricted read-only access.

The `ChangebaleHashSet` actually already implements ICollection, what I would suggest to add are:
* `ChangeableIndexList `does not implement anything -> add `IList`
* `ChangeableHashMap` only implement `IEnumerable` -> add `IDictionary`

**Comment by krauthaufen** [comment]
> ChangeableHashMap only implement IEnumerable -> add IDictionary

Sadly this can't be done without also implementing `IEnumerable<KeyValuePair<'K, 'V>>` and `IEnumerable<KeyValuePair<'K, 'V>>` and that would break lots of code since currently the map is `IEnumerable<'K * 'V>`

**Comment by luithefirst** [comment]
I did not inspect that in detail and was not aware of that this would break the implementation. Breaking changes were not intended when opening the issue, if this comes up again we should discuss this separately. 

So I look like this would only leave adding `IList` to `ChangeableIndexList`.

**Comment by krauthaufen** [comment]
i did all implementations (except for `IDictionary`) in the [v110](https://github.com/fsprojects/FSharp.Data.Adaptive/tree/v110) branch and I think we should continue there (it's just better-enumerators currently)

**Comment by krauthaufen** [comment]
Also i added `transactIfNecessary` to all the interface implementations, s.t. people using `IList`, etc. don't need to know that it's an adaptive datastructure

**Comment by krauthaufen** [comment]
done in `v110`
