### ISSUE TITLE
manipulating cset/clist/cmap/cval without transcation

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#79]
I've noticed that the current behavior when manipulating cset/clist/cmap/cval without a transcation (and not outputs) is not consistent. I would prefer that manipulation are possible as long as there are no outputs. The units test committed here fail in some cases: https://github.com/fsprojects/FSharp.Data.Adaptive/commit/96d59708a1260384280cfa7079bc6be54e381bc9

It turns out when the internal state is set to be "updated", manipulations fail in some cases afterward.

**Comment by luithefirst** [comment]
The reason for the failed test is that the `cset` contains a `history |> AVal.map CountingHashSet.toHashSet` internally and the `AdaptiveObject` becomes an output as soon as the content is queried. I'm not sure what we could do about that.

**Comment by krauthaufen** [comment]
Actually I think this an extreme corner-case here but nonetheless it could be done.
I implemented it for `cset<'T>` in https://github.com/fsprojects/FSharp.Data.Adaptive/commit/a3a09ea7f4ce97df8710fcfcf5c19a29059d0475

**Comment by krauthaufen** [comment]
all your tests are green in https://github.com/fsprojects/FSharp.Data.Adaptive/commit/3d7acccdc607ca6c02805ba107593238a618b7d8
