### ISSUE TITLE
applyDelta Test fails rarely

### ISSUE THREAD

**Issue by krauthaufen** [fsprojects/FSharp.Data.Adaptive#94]
See https://github.com/fsprojects/FSharp.Data.Adaptive/actions/runs/1438879548

**Comment by luithefirst** [comment]
I can reproduce that locally, but it does not make sense to me. Similar to the case that fails in the log, I get an error while the input was an empty set and a map with 3 deltas. When I try to reproduce it by hardcoding the inputs of the test to those values, it passes. In the case of running it with the automated test, it fails at Set.check that shows inputs with strange values where I have no idea where they are coming from.

**Comment by krauthaufen** [comment]
Thanks for looking into that, i'll have time for this tomorrow, so I'll try to find it...

**Comment by krauthaufen** [comment]
It must be a pretty rare case, since fscheck almost never finds it...

**Comment by krauthaufen** [comment]
Thanks, that'll help finding the problem

**Comment by luithefirst** [comment]
and also "let d = Map.ofList [({ value = 23 }, 1); ({ value = 87 }, -1); ({ value = 407 }, 1)]" as in the log you posted
